- docs/comparison.adoc
It seems like :toc: does not handle well links in titles. Links have been put to the references list in order to allow to use the ToC with more ease.
> Fixed weird ToC behaviour

- js/openlocationcode.js
This should resolve #24 - the library will also work in node.js and other commonjs-style environments (such as CouchDB), but also in browser environments with AMD without polluting the global namespace.
Of course, simply including the file via script tag is still working.
I used the [returnExportsGlobal](https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js) variant.
> added an UMD style wrapper

- ruby/open-location-code.gemspec
I added gemspec file for publishing @wnameless 's ruby implementation to rubygems.org.
wnameless has already published https://github.com/wnameless/plus_codes-ruby gem, however, I prefer publishing gem from this official repository to wnameless's third-party repository. Because it makes easier for us to maintain codes, for users to find out this library.
@drinckes @wnameless How do you think about that?
I already signed the Contributor License Agreements.
> Add Ruby gemspec file

- README.md
This makes it easier to view the current build status and to find the Travis CI
page for the project.
> Add Travis build status to front page.

- visualbasic/OpenLocationCode.bas
Fix typo in one of the error messages in the test section. This doesn't affect operation of the library. See issue #66.
> Fix VBA test message

- .travis.yml
- run_tests.sh
- rust/Cargo.toml
- rust/src/codearea.rs
- rust/src/consts.rs
- rust/src/interface.rs
- rust/src/lib.rs
- rust/src/private.rs
- rust/tests/all_test.rs
- rust/tests/csv_reader.rs
working implementation (passes all validation, enc/dec, shorten/recover unit-tests); probably room for improvement wrt comments, layout.
> Initial rust implementation

- .travis.yml
Newly added rust configuration breaks the travis CI tests (see #75), so temporarily (hopefully) commenting the rust config out.
> Comment out rust config from travisci

- java/com/google/openlocationcode/OpenLocationCode.java
Both constructors claim that they might throw an IllegalArgumentException via comment, but only one of them actually declares as much. Add "throws" clause to other constructor for consistency.
> declare exception throwing in constructor

- python/openlocationcode.py
- Valid lengths are divisible by 2 until the pair code length, not separator position.
> Fixed codeLength input validation in the encode method.

- rust/src/interface.rs
- rust/src/private.rs
* Use `position()` on `iter()` instead of loop in `code_value`
* Use arithmetic operator in `normalize_longitude`
* Use `powi` for integer power (`-3`) in `compute_latitude_precision`
* Use arithmetic operators in `encode`
* Reserve String space (`/cpp/openlocationcode.cc`) in `encode`
> Changes to Rust implementation

- rust/src/private.rs
> Fix typo in rust function

- .travis.yml
- java/com/google/openlocationcode/tests/ShorteningTest.java
- python/openlocationcode_test.py
See issue #98 
This adds all implementations (except visualbasic since it's a spreadsheet macro) to the travis CI testing.
In the process this identified an encoding bug in the python test script, and that the Java implementation was not reading the test data correctly.
> Update travis.yml, add all implementations

- cpp/openlocationcode.cc
- test_data/shortCodeTests.csv
There was a typo in the C++ fix for #89 but it wasn't exercised by any tests.
This adds tests for codes with reference locations in the neighbouring 4-digit cell and confirms they shorten and recover correctly.
> Fix #89 for C++, add further tests

- cpp/openlocationcode_example.cc
Fixed unused variable compilation errors in the cpp example program. Also removed dependency on "using namespace std;".
> Make cpp example compile

- cpp/openlocationcode.h
- cpp/openlocationcode_test.cc
Make argument name in .h the same as .cc, and change an arg to a const in the test code.
> Fix cpp argument naming and usage.

- ruby/open-location-code.gemspec
for releasing a new version by ruby gem because of this [bug](https://github.com/google/open-location-code/issues/89)
> update ruby gem version to 1.0.2

- android_demo/android/libs/README.md
Changed directions to include *.classes instead of *.java
Android Studio now recognizes .JAR when added as project dependency.
> Modified instructions

- python/openlocationcode.py
Description of recoverNearest claims that a valid full code will be returned unchanged. As implemented, actually raises a ValueError. Fixed by returning a valid full code properly capitalized, but otherwise unchanged.
> Fix issue #128 (recoverNearest for full OLC)

- java/com/google/openlocationcode/OpenLocationCode.java
javadoc does not have a @constructor tag, because unlike javascript, in Java it is always clear which function is a constructor and which is not.
> Removed invalid @constructor tag - not in javadoc

- WORKSPACE
- cpp/openlocationcode.cc
Slight performance improvement by negating a value that is known to be
negative instead of calling fabs().
Copied from #150.
> Replace fabs call in C++ implementation.

- js/closure/BUILD
This way the Closure Compiler needs to be run 693 fewer times.
$ bazel query 'kind(closure_js_library, deps(//js/closure/...))' | wc -l
802  # <-- before
109  # <-- after
Notes:
1. These build rules export the world, for the sake of convenience:
- `@io_bazel_rules_closure//closure/library`
- `@io_bazel_rules_closure//closure/library:testing`
2. closure_js_library has an implicit dependency on base.js.
3. rules_closure runs jscomp on each closure_js_library.
> Use fine-grained closure_js_library deps

- cpp/openlocationcode.cc
Remove single use of std::begin() and std::end() on a const char array. std::end() is actually incorrect for this use since it returns the end location AFTER the terminating null character so std::find() would match any null character in the string (although there are none). Replace std::end() with internal::kAlphabet + internal::kEncodingBase, consistent with a very similar std::find() search earlier in the code.
> Remove use of std::begin() and std::end()

- cpp/codearea.cc
Fix structure initialization syntax which is non-standard and "obsolete since GCC 2.5" (https://gcc.gnu.org/onlinedocs/gcc-4.8.1/gcc/Designated-Inits.html). Just use the C99 style, as anything else doesn't work with even recent Microsoft compilers.
Also tidy up the formatting in the rest of the function.
TESTED=all tests pass
> Fix obsolete structure init in CodeArea::GetCenter()

- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
No need to create a new BigDecimal(0); we can use the static BigDecimal.ZERO instead.
> Use BigDecimal.ZERO in Java implementation

- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
From Effective Java item 62: "Use the Javadoc @throws tag to document each unchecked exception that a method can throw, but do not use the throws keyword to include unchecked exceptions in the method declaration."
> Don't include unchecked exceptions in method signature in Java library.

- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
Using hashCode() can provide false positives due to collisions. Instead, we should directly check that the codes are equal.
> Change equals() to directly check code equality in Java library.

- tile_server/gridserver/geojson.go
- tile_server/gridserver/geojson_test.go
- tile_server/gridserver/gridserver.go
- tile_server/gridserver/image.go
- tile_server/gridserver/image_test.go
- tile_server/gridserver/tileref.go
- tile_server/main.go
This exports the tile option fields so they can be accessed from outside the package.
> Export tile option fields

- tile_server/gridserver/tileref.go
Colours aren't relevant for JSON tiles, so they don't need to be returned in the string representation of the options.
The background is that this string might be used to cache the output or store it in files.
> Drop colours from JSON option strings

- java/README.md
- java/pom.xml
New version available at https://search.maven.org/artifact/com.google.openlocationcode/openlocationcode/1.0.1/jar.
> Bump Java version to 1.0.1.

- cpp/openlocationcode.cc
- cpp/openlocationcode.h
- cpp/openlocationcode_test.cc
I realized this constant was unused when I was cloning the C++ tests into the C implementation.
I am not 100% sure if it is OK to remove this (the repo doesn't reference it at all), so please feel free to reject this PR if this is wrong.
> Remove unused constant kMinShortenDegrees

- c/Makefile
- c/example.c
- c/olc.c
- c/olc.h
- c/olc_private.h
- c/olc_test.c
- c/tests.h
Bug was due to two things (so, maybe two bugs):
1. Not considering the full size of a 16 characters code.
2. Not correcting the top position when the code includes a separator,
which made it process fewer grid square characters.
A new test was added to make sure this is (and remains) fixed.
> Fix decoding bug in C implementation

- .travis.yml
- c/Makefile
Compilers are sensitive to the presence and order of -lm.
> Add C implementation to TravisCI config

- garmin/PlusCodeDatafield/manifest.xml
https://developer.garmin.com/index.php/blog/post/changes-to-the-position-permission: "In the past developers have had access to the user’s position via the Toybox.Activity.Info.currentLocation without a permission. This API provides live position information to data fields operating within an activity, and can be used by Watch Faces to acquire a last known location. In an upcoming change to Connect IQ, we will be changing the behavior of this API and require the Position permission. This change will be made retroactively back to Connect IQ 1.x devices, so developers should add the Position permission to their apps (including for Connect IQ 1.x products) before June 30th. Failure to do so will cause your apps to stop working after this change is implemented."
> Add "Positioning" permission to the app

- c/example.c
- c/olc.h
- c/olc_test.c
We define the customary macros to be able to get the library version as
a comparable number, a printable string and as separate numeric values
for major, minor and patch.  Test included.  Arbitrarily start at 1.0.2.
> Add library version information

- swift/README.md
This library now supports Swift 4.2
https://github.com/curbmap/OpenLocationCode-swift/blob/master/CHANGELOG
> Update version for Swift

- garmin/PlusCodeDatafield/README.md
- garmin/PlusCodeDatafield/monkey.jungle
Current Connect IQ SDK (v3) has removed some command line flags and replaced them with [`jungle`](http://developer.garmin.com/connect-iq/programmers-guide/overriding-resources/) files. (I think they're carrying on with the monkey thing a bit much tbh.)
> Update Garmin build files and docs

- js/src/openlocationcode.js
correct JSDoc duplicated 'latitude' by 'longitude'
> [JSDoc] typo

- python/BUILD
Anyone pulling in the library using Blaze/Bazel currently won't be able to reference the library. This updates the default visibility to public.
> Update Python library visibility to public.

- .travis.yml
- go/README.md
- go/olc_test.go
- go/shorten.go
Add in a check in the continuous integration to fail if Go files are not formatted correctly.
Format the current Go files.
> Require Go files to be correctly formatted

- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
- test_data/validityTests.csv
The API reference for the isValid() method specifies:
> There must be an even number of at most eight characters before the separator.
The current Java implementation fails to validate that there are at most eight characters before the separator.  For example, these invalid codes would pass the isValid check and ultimately break the operations.
```
8FWC2345G6+
8FWC2345G600+
8FWC2345G62222222222+
```
This PR fixes this by checking that the separator position is also not greater than 8 just like the other implementations do.
One of the above examples was also added to `validityTests.csv` to validate this test case.
> Fix Java isValidCode() to validate separator position as defined by the spec

- test_data/shortCodeTests.csv
Per https://github.com/google/open-location-code/issues/128, when passed a full code, the recover function should return the full code.
This PR adds test data to verify that behavior.
> Add test data to verify behavior of recovering full codes

- cpp/openlocationcode.cc
- dart/lib/src/open_location_code.dart
- go/shorten.go
- js/closure/openlocationcode.js
- js/src/openlocationcode.js
- ruby/lib/plus_codes/open_location_code.rb
- rust/src/interface.rs
- test_data/shortCodeTests.csv
Unify the behavior when a full code is given to `recoverNearest` with lowercase characters by always returning the uppercased code. Currently, some implementations return the uppercased full code while others will return it unmodified.
Rolls out changes made in #128 to the Python implementation (`recoverNearest` returns uppercased full code) to remaining implementations.
> Return uppercased code in recoverNearest in all implementations

- swift/README.md
Update Swift README to include reference to the [Open Location Code for Swift and Objective-C](https://github.com/google/open-location-code-swift) project
Documented several properties of the two available implementations to help people decide which better suits their needs.
Rendered markdown staged [here](https://github.com/WilliamDenniss/open-location-code/tree/swift/swift).
> Update Swift README

- js/package.json
- js/test/gulpfile.js
Fix failing JS tests.
NodeJS tests were failing with:
```
9.31s$ cd js && npm install && npm test
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: …
```
> Update gulp version, remove dependency on gulp-util

- c/Makefile
- c/olc.c
- c/olc_test.c
- c/tests.h
See #288 
Also made it so failing C tests would actually fail! And fixed bug in OLC_RecoverNearest that would fail if passed a full code.
> Update C test for the split encoding/decoding tests

- .bazelrc
- .travis.yml
- WORKSPACE
This now uses the current bazel release, so that tests can be run locally without having to push to travis all the time.
Took the opportunity to set up travis caching for ruby, and for the js/closure project, so it doesn't need to build the bazel dependencies (com_google_protobuf etc) every time. This reduces the time to run the closure tests from over seven minutes to just under two.
> Update WORKSPACE to support Bazel 0.24

- c/Makefile
- c/olc_test.c
If the C tests fail, the test command exited with zero so the TravisCI test page would indicate a pass.
Not unless you looked at the test output would you discover a failure.
> Make failing C tests actually fail

- rust/src/consts.rs
- rust/src/private.rs
The error compensation is applied with precision of 1e-9, seems precise enough for existing code length.
https://github.com/google/open-location-code/issues/317
> Fix error accumulation issue caused by floating point precision

- java/BUILD
- java/src/test/java/com/google/openlocationcode/BenchmarkTest.java
- java/src/test/java/com/google/openlocationcode/PrecisionTest.java
Adds a benchmark test that calls the encoding and decoding functions and outputs the durations.
This helps identify if changes have impacted performance.
Also adds an epsilon into the precision tests.
> Add benchmarks to Java

- ruby/lib/plus_codes.rb
- ruby/lib/plus_codes/code_area.rb
- ruby/lib/plus_codes/open_location_code.rb
- ruby/open-location-code.gemspec
- ruby/test/plus_codes_test.rb
Adding these comments to each file enables immutable string literals - which Ruby is working towards for Ruby 3.0.
This was identified by the [Rubocop](https://github.com/rubocop-hq/rubocop) checks failing. This was due to the fact that their release 0.69.0 turned this check on always, instead of optionally or off or something as part of their migration off Ruby 2.2.
> Enable immutable string literals in Ruby

- .travis.yml
- rust/Cargo.toml
- rust/README.md
- rust/src/codearea.rs
- rust/src/consts.rs
- rust/src/interface.rs
- rust/src/lib.rs
- rust/src/private.rs
- rust/tests/all_test.rs
- rust/tests/csv_reader.rs
This adds benchmarks of the `encode` and `decode` functions to the Rust tests.
It also formats the code using `rustfmt` and enforces the formatting in the TravisCI configuration.
> Add Rust benchmarks

- rust/src/consts.rs
- rust/src/interface.rs
- rust/src/private.rs
Fix final floating point tests in rust implementation by using integer operations for encode and decode.
> Fix floating point tests in Rust implementation 

- rust/src/interface.rs
In Rust, a leading underscore in a variable name/argument name means that the variable is unused, which isn't the case here. This PR impacts the generated documentation / readability of the code, but otherwise impact behavior.
It would also be more idiomatic to avoid allocating Strings instead these functions in a couple places either by avoiding mutation altogether (there's no need to physically remove the padding characters) or by having functions take Strings instead of &str's. However, such changes would be more invasive so I held off doing them for now
> Make argument names more idiomatic

- .travis.yml
Per https://github.com/google/open-location-code/issues/369#issuecomment-569322868 , Python 3.6 is already tested, however https://github.com/google/open-location-code/issues/369 states:
> the Python module does not work in Python 3.7
So, adding python 3.7 and 3.8, which have some potentially breaking changes, to the build matrix for continuous testing.
> Add Python 3.7, 3.8 and openjdk>8 to build matrix

- dart/pubspec.yaml
If the environment constraint is not specified, it automatically means the package only supports Dart SDK < 2.0.0, preventing the library from being used with the most recent Dart version (currently 2.8.3).
> Update Dart SDK constraint to allow SDK versions up to 3.0.0.

- ruby/open-location-code.gemspec
- ruby/rubocop.yml
- ruby/test/plus_codes_test.rb
Use named references in printf.
Set LineLength to 80 in rubocop config to match project convention and prevent IfUnlessModifier offenses.
Specify required_ruby_version >= 2.4 in gemspec
> Fix rubocop offenses

- rust/src/codearea.rs
Remove redundant field names in struct initialization 
Fixes #404
Rust tests run and successfully completed
> Rust: Remove redundant field names

- rust/src/interface.rs
Remove unneeded return statement from end of function. 
Expressions at end of function are automatically returned
Tests as per travis.yml carried out successfully
Fixes #405
> Remove unneeded return statement

- rust/src/consts.rs
Remove redundant static lifetime from constant. 
Constants have by default a static lifetime
Fixes #403
> Remove redundant static lifetime from constant

- docs/specification.md
The correct calculation for the least-significant digits is:
4*(latitude % 5) + (longitude % 4)
This is the formula used in many different implementations:
[C++](https://github.com/google/open-location-code/blob/84f0adbdbfec7b165cdbb419f36cc62b78761533/cpp/openlocationcode.cc#L151)
[Java](https://github.com/google/open-location-code/blob/84f0adbdbfec7b165cdbb419f36cc62b78761533/java/src/main/java/com/google/openlocationcode/OpenLocationCode.java#L223)
[TypeScript](https://github.com/tspoke/typescript-open-location-code/blob/d61f5081a8a830409fee43f0711889c4c6478546/src/open-location-code.ts#L308)
The previous documentation had this incorrect instruction:
(latitude % 5) * (longitude % 4)
> Fix encoding steps for grid digits

- dart/lib/src/open_location_code.dart
- dart/test/benchmark_test.dart
- dart/test/clip_latitude_test.dart
- dart/test/compute_precision_test.dart
- dart/test/decode_test.dart
- dart/test/encode_test.dart
- dart/test/short_code_test.dart
- dart/test/utils.dart
- dart/test/validity_test.dart
Following the style suggestion in [effective dart](https://dart.dev/guides/language/effective-dart/design#avoid-type-annotating-initialized-local-variables)
#omit_local_variable_types
> Noop: Omit type annotations for local variables. 

- rust/Cargo.toml
- rust/src/interface.rs
- rust/tests/all_test.rs
The Rust library depends on rather outdated versions of `geo` and `rand` so this PR upgrades to the most recent ones. To be usable with the wider ecosystem, a new version will have to be pushed to crates.io so I've bumped the library version accordingly.
> Upgrade rust library dependencies and bump version

- API.txt
This file still mentioned both a "prefix character" and an "optional separator". This must be outdated references to a previous OLC format ("+xxxx.xx") that no longer exist elsewhere in the specifications. This changes removes these references.
> Remove refs to "prefix" and optional separator

- cpp/openlocationcode.h
Fixing https://github.com/google/open-location-code/issues/442 by not calling a small area a point.
> Reword description

- python/openlocationcode/openlocationcode.py
Comment for recoverNearest mentioned a previous code format that is no longer in use.
This PR fixes https://github.com/google/open-location-code/issues/456
> Remove references to outdated code format

- ruby/open-location-code.gemspec
- ruby/rubocop.yml
To match the default value rubocop has set as required.
* Fixing `Gemspec/RequiredRubyVersion: required_ruby_version (2.4, declared in open-location-code.gemspec) and TargetRubyVersion (2.5, which may be specified in .rubocop.yml) should be equal.` error (from https://travis-ci.org/github/google/open-location-code/jobs/769484507)
* 2.5 is the oldest supported version: https://github.com/rubocop/rubocop/blob/51bac9d21fbe245b69d4a3d8c067915dabd7747e/config/default.yml#L141
* Also updating our `.rubocop.yml` to hardcode the TargetRubyVersion to be 2.5 to avoid this error in the future (https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version).
> Update TargetRubyVersion in gemspec to be oldest official supported ruby version

- .github/workflows/main.yml
- WORKSPACE
- ruby/lib/plus_codes/open_location_code.rb
- ruby/open-location-code.gemspec
- ruby/rubocop.yml
Fixing CI build issues:
1. ruby issues: (support for 2.5 dropped by rubocop: https://github.com/rubocop/rubocop/commit/1a60305ffbeb6128d29b631628167e832e21bd9f)
1. `rubocop-ast requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.` 
2. `Style/SlicingWithRange: Prefer ary[n..] over ary[n..-1].`
2. js-closure issue: `Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found`
> Fix ruby/js build issues

- API.txt
At most six digits can be removed to result in a valid short Plus Code.
> Update API.txt to clarify the conflict with specification.md

- cpp/openlocationcode.cc
Without this change the code can not be compiled with the latest GCC 13 because an error reported on `openlocationcode.cc:139:3`.
```
error: 'int64_t' was not declared in this scope
note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```
The porting guide of GCC 13 explains,
that `cstdint` might need to be explicitly included: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
> Fix missing cstdint on GCC 13

- .github/workflows/main.yml
From #559 (bot authored, CLA not signed):
> In our analysis, we observe that this target/surefire-report/ directory is generated but not later used during the CI build. Hence, we propose to disable generating this directory to save runtime.
The generation of this directory can be disabled by simply adding -Dsurefire.useFile=false -DdisableXmlReport=true to the mvn command.
> Update main.yml to ignore unnecessarily generated surefire-report

- .github/workflows/main.yml
This changes the python versions to the current stable (3.14) and the bug fix releases (3.13, 3.12).
See issue #645.
> Update python versions used for testing

- python/openlocationcode_test.py
Addresses part of issue #645
At some point (python 3?) this started requiring the directory name as a prefix.
> Correct path to openlocationcode package in python tests

- .github/workflows/main.yml
For issue #645 
Earlier, removed python2 from the versions being installed for python tests, so we need to use python3 in the `DIFF` command line.
> Use python3 for diffing

- python/openlocationcode_test.py
Correct python test file for `yapf` detected formatting errors.
> Correct python format

- ruby/test/plus_codes_test.rb
Issue #643 
`rubocop` was complaining about the use of parentheses, this removes them.
> Fix ruby/rubocop formatting

- .bazeliskrc
- .github/workflows/main.yml
- MODULE.bazel
- WORKSPACE
- js/closure/BUILD
- js/closure/openlocationcode_test.js
For issue #659 
This adds an action to use `bazelisk` to fetch a specific `bazel` version, configured to 7.4.1 in the `.bazeliskrc` file.
It adds back the `WORKSPACE` file, since the Bazel Closure Rules package does not support the new bazel modules.
Finally it updates the dependencies for the JS Closure test, and the path to the test data files.
> Updates for bazelisk support

- MODULE.bazel
Issue #659 
Update module versions in Bazel configuration to latest, and remove the ones that aren't necessary.
> Update Bazel module versions

- Documentation/Specification/specification.md
Change "Open Location Code" to "Plus Code" when talking about individual codes, as per naming convention.
> Complete applying naming conventions to specification.md (OLC vs. Plus Code)

- .github/workflows/main.yml
- go/olc_gofuzz.go
Update the Go version used for the CI tests to the current stable 1.23
This will unblock PR #681
> Update Go version to 1.23

- js/README.md
The jsfiddle link is broken and I changed it to a working one.
> Fix broken examples jsfiddle link in js/README.md

- cpp/openlocationcode.cc
For issue https://github.com/google/open-location-code/issues/672
This modifies the integer conversion in the C++ implementation to resolve floating point precision inconsistencies.
It doesn't yet expose the integer-based encoding as a separate function as I'm hopeful we can resolve our problems without having to do that.
> Modify C++ floating point conversion for encoding

- go/decode.go
- go/encode.go
- go/olc.go
- go/olc_test.go
For issue https://github.com/google/open-location-code/issues/672
This modifies the integer conversion in the Go implementation to resolve floating point precision inconsistencies.
It doesn't yet expose the integer-based encoding as a separate function as I'm hopeful we can resolve our problems without having to do that.
It also cleans up a bunch of static analysis warnings (unused code etc).
> Modify integer conversion for Go library

- go/decode.go
- go/encode.go
- go/olc.go
This refactors the `Encode()` and `Decode()` functions in order to improve readability.
The `Decode()` function gets a performance bonus - almost 10% faster, dropping from 285.3 ns/op to 262.5 ns/op.
Before:
```
BenchmarkEncode
BenchmarkEncode-14      31356085                34.69 ns/op           16 B/op          1 allocs/op
BenchmarkDecode
BenchmarkDecode-14       4183998               285.3 ns/op            24 B/op          1 allocs/op
```
After:
```
BenchmarkEncode
BenchmarkEncode-14      34198537                35.92 ns/op           16 B/op          1 allocs/op
BenchmarkDecode
BenchmarkDecode-14       4551160               262.5 ns/op            24 B/op          1 allocs/op
```
> Refactor golang encode and decode

- js/closure/openlocationcode.js
- js/src/openlocationcode.js
For issue #710 
JS implementations round the coordinates in the results from `Decode()`. If this is to enable tests to pass then that should be done in the tests, not by fudging the actual return values.
> remove rounding in decode results

- c/src/olc.c
Closes #672 
The C encode function was split into a public method with floats, and a private one with integers. The intent was to use this from tests, but it turned out that I could make all the implementations play nice with the floats in the test files.
This rejoins the split function.
> rejoin split encode function

- c/src/olc.c
- c/src/olc.h
- cpp/openlocationcode.cc
- cpp/openlocationcode.h
- dart/lib/src/open_location_code.dart
- go/encode.go
- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
- js/closure/openlocationcode.js
- js/src/openlocationcode.js
- plpgsql/pluscode_functions.sql
- plpgsql/tests_script_l.sql
- python/openlocationcode/openlocationcode.py
- ruby/lib/plus_codes/open_location_code.rb
- rust/src/interface.rs
- rust/src/lib.rs
- visualbasic/OpenLocationCode.bas
Fixes #672 
This is because we cannot rely on "correct" conversions from the floating point coordinates in degrees to integer values. So we need to split the encode methods, and test using integer values against an integer encoding method.
> Split encoding implementations into integer encoding method

- c/openlocationcode_test.cc
- cpp/openlocationcode.cc
- cpp/openlocationcode_test.cc
> cpp: use floor for integer conversion

- dart/lib/src/open_location_code.dart
- dart/test/encode_test.dart
See issues https://github.com/google/open-location-code/issues/674 and https://github.com/google/open-location-code/issues/717.
> dart: use floor for conversion, add integer tests

- go/encode.go
- go/olc.go
- go/olc_test.go
See issues https://github.com/google/open-location-code/issues/674 and https://github.com/google/open-location-code/issues/717.
> go: use floor for conversion, use integer tests

- java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
- java/src/test/java/com/google/openlocationcode/EncodingTest.java
See issues https://github.com/google/open-location-code/issues/674 and https://github.com/google/open-location-code/issues/717.
> java: use floor for conversion, add integer tests

- js/closure/openlocationcode.js
- js/closure/openlocationcode_test.js
See issues https://github.com/google/open-location-code/issues/674 and https://github.com/google/open-location-code/issues/717.
> js/closure: use floor for conversion, add integer tests

- js/README.md
- js/src/openlocationcode.js
- js/test/jasmine-tests.js
See issues #674 and #717.
The tests are refactored to put [Jasmine](https://jasmine.github.io/) specs (`it()` clauses) around each expectation.
> js: use floor for conversion, add integer tests
