go/decode.go, go/encode.go, go/olc.go, go/olc_gofuzz.go, go/olc_gofuzz_test.go, go/olc_test.go, go/shorten.go
I don't know whether is this feasible or not, I understand if not (maintenace of Go code...),
but I'd be happy if I could contribute that code into this project.
This code has been first published at github.com/tgulacsi/golc, if this PR is accepted, I'll close that down, and redirect people to here.
=> Initial Go commit.

java/codes/plus/OpenLocationCode.java, java/codes/plus/tests/EncodingTest.java, java/codes/plus/tests/PrecisionTest.java, java/codes/plus/tests/ShorteningTest.java, java/codes/plus/tests/ValidityTest.java, java/java.iml
Hi Doug, here is my Java implementation. Please have a look when you have time.
I mostly wrote it based on the refernce, not the JavaScript versions, therefor there are slight differences and I had to touch the test data. Sometimes I just added a test data to cover more case.
=> Initial Java implementation.

ruby/lib/plus_codes.rb, ruby/lib/plus_codes/code_area.rb, ruby/lib/plus_codes/open_location_code.rb, ruby/test/plus_codes_test.rb
I made a Ruby implementation of the Open Location Code algorithm, I would like to share this to the repository. BTW, I already signed the Contributor License Agreements.
=> Add Ruby implementation

java/com/google/openlocationcode/OpenLocationCode.java, java/com/google/openlocationcode/tests/EncodingTest.java, java/com/google/openlocationcode/tests/PrecisionTest.java, java/com/google/openlocationcode/tests/ShorteningTest.java, java/com/google/openlocationcode/tests/ValidityTest.java
Google-originated open source projects should follow the [Google Style Guide](https://github.com/google/styleguide). The Java style guide can be found [here](https://google.github.io/styleguide/javaguide.html).
=> Format code to Google Java Style Guide standards.

ruby/README.md
This README.md is created because of drinckes's suggestion
=> Add README.md to /ruby

java/com/google/openlocationcode/OpenLocationCode.java
The class should never be subclassed.
=> Make Java OpenLocationCode class final.

visualbasic/OpenLocationCode.bas, visualbasic/README.md
Add a VBA implementation to allow codes to be created and decoded within spreadsheets.
=> Add visual basic (VBA) implementation

java/.gitignore, java/README.md, java/com/google/openlocationcode/OpenLocationCode.java
This refactors the Java implementation - slightly changing the code, but mostly changing to constants, changing variable names and comments to make the code clearer.
It also adds a README with instructions on running the tests.
Texts executed and pass:
```shell
$ java -cp $CLASSPATH:build:../test_data: org.junit.runner.JUnitCore com.google.openlocationcode.tests.EncodingTest com.google.openlocationcode.tests.PrecisionTest com.google.openlocationcode.tests.ShorteningTest com.google.openlocationcode.tests.ValidityTest
JUnit version 4.12
...........
Time: 0.054
OK (11 tests)
```
See issue #69 .
=> Refactor java implementation

.gitignore, CONTRIBUTING.md, TESTING.md, WORKSPACE, cpp/WORKSPACE, java/BUILD, java/README.md, java/com/google/openlocationcode/tests/EncodingTest.java, java/com/google/openlocationcode/tests/ShorteningTest.java, java/com/google/openlocationcode/tests/ValidityTest.java, js/closure/BUILD, js/closure/README.md, js/closure/openlocationcode.js, js/closure/openlocationcode_test.js, test_data/BUILD
This adds a JS implementation suitable for the Google Closure JS Compiler.
It also adds Bazel BUILD files with test configurations for the C++ and JS closure implementations, rewrites CONTRIBUTING.md, and adds a Bazel section to TESTING.md.
=> Add Closure JS implementation

js/closure/openlocationcode.js, js/closure/openlocationcode_test.js
This changes the namespace of the closure module to remove the google reference, and allows other modules to be defined within it.
=> Closure namespace

python/pluscodes.py, python/testpluscodes.py
Python implementation of open-location-code, tested using unittest
=> python implementation

dart/lib/src/open_location_code.dart
=> codeLength input validation

go/encode.go
=> go: code length validation in encode

ruby/lib/plus_codes.rb, ruby/lib/plus_codes/open_location_code.rb, ruby/test/plus_codes_test.rb
=> ruby code length validation

rust/src/interface.rs
Use `PAIR_CODE_LENGTH` constant which defined in `src/constants.rs`.
=> Use constant for data validation

.travis.yml, run_tests.sh
#75 
[`matrix:include`](https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages) allows multi language support so I've added the rust setup again and it seems running normally.
=> #75 Fix rust setup.

swift/README.md
=> Add link to Swift 3.x implementation.

rust/src/interface.rs, rust/tests/all_test.rs
=> Fix recovery bug in Rust

java/com/google/openlocationcode/OpenLocationCode.java, java/com/google/openlocationcode/tests/RecoverTest.java
This fixes issue #89 for Java and adds the tests as outlined. Also fixes an unrelated typo (line 152).
=> Java: fixing issue #89 and adding tests

cpp/BUILD, cpp/README.md, cpp/openlocationcode.cc, cpp/openlocationcode_test.cc
Address issue #89.
Tests were not reading from CSV files either (!).
=> Fix recovery bug in cpp

visualbasic/OpenLocationCode.bas
Address issue #89.
Added tests, confirmed they fail in LibreOffice, updated code and confirmed tests pass again.
=> Fix recovery bug in VB

dart/lib/src/open_location_code.dart, dart/test/all_test.dart
=> Fix recovery bug in dart

.travis.yml, python/openlocationcode_test.py
Modify calls to open() to be compatible with both python 2 & 3.
Some formatting changes.
=> Update openlocationcode_test.py for Python2

java/BUILD
Remove unnecessary data dependencies.
=> Add RecoverTest to Java BUILD

cpp/openlocationcode_test.cc
Adds a test to make sure the tests are not empty.
=> Ensure C++ tests are not empty

java/BUILD
Reformat Java build file with https://github.com/bazelbuild/buildtools
=> Format Java BUILD file

cpp/openlocationcode_test.cc
Replace calls to atof() with strtod()
=> c++: Use strtod

cpp/BUILD
=> Reformat cpp/BUILD

js/README.md
For semantic and proper understanding.
=> Minor adjustment (proposal)

csharp/README.md
As discussed [here](https://github.com/google/open-location-code/pull/68#issuecomment-366687719)
=> Add link to C# .NET Standard implementation

.bazelrc, .travis.yml, WORKSPACE, js/closure/BUILD, js/closure/openlocationcode.js, js/closure/openlocationcode_test.js
Update Bazel from 0.5.3 to 0.14.0.
=> Update Bazel version in TravisCI

java/pom.xml
Version 1.0 is now available in MavenCentral. You can see the code here:
https://oss.sonatype.org/content/groups/public/com/google/openlocationcode/openlocationcode/
I'll add some README instructions in a separate PR. The issue I opened to get a repo set up is at https://issues.sonatype.org/browse/OSSRH-40363.
#152
=> Add config for including library in MavenCentral.

js/README.md
Please merge this pull request to get cdnjs link from the readme doc.
=> Updated a cdnjs link for openlocationcode

tile_server/gridserver/testdata/5_17_19_geodetic.json
Format JSON data file so it is easily readable.
=> Format JSON test file

c/.gitignore, c/Makefile, c/README.md, c/example.c, c/olc.c, c/olc.h, c/test_csv.c
I based this implementation on the C++ code, so all the original ideas and knowledge comes from there and are not mine.
I used a simple Makefile to not have to deal with external dependencies while I developed / tested; I  intended to move this to use the standard Google tools, but found myself short of time, so I decided to just go ahead and create the PR as is. Please let me know if this is a problem.
Cheers,
Gonzalo
=> C implementation of the Open Location Code API

c/.gitignore, c/Makefile, c/README.md
Create a static library
Add target to install
=> Improve c-version Makefile

.travis.yml, go/olc_test.go
Add benchmarks to go implementation tests.
=> Add go benchmarks

docs/olc_definition.adoc
=> Clarify sizes of 11-digit code areas

where_am_i/README.md, where_am_i/index.html, where_am_i/location.js
Includes capability to convert the plus code to a compound code through passing an API key.
=> Add page to display the user's location as a plus code.

README.md
README update to add link to wiki on line 72 to make it intuitive
=> Added link to wiki on line 72 to make it intuitive

go/olc_test.go
Fixes #281.
There may be a way to fix this bug while keeping the separate testing package, I'm am keen to hear from a Go expert.
Example [Travis run](https://travis-ci.org/WilliamDenniss/open-location-code/builds/521951545) with this fix (where a broken go build is expected).
=> Modify import for go tests to use local package

go/olc_test.go
=> Update golang for split tests

java/BUILD, java/src/main/java/com/google/openlocationcode/OpenLocationCode.java, java/src/test/java/com/google/openlocationcode/DecodingTest.java, java/src/test/java/com/google/openlocationcode/EncodingTest.java, java/src/test/java/com/google/openlocationcode/UtilsTest.java
See issue #288 
This PR also adds a length attribute to the Java CodeArea object.
=> Add length to Java CodeArea object (and update for split test files)

ruby/lib/plus_codes/code_area.rb, ruby/lib/plus_codes/open_location_code.rb, ruby/test/plus_codes_test.rb
Also updates tests for the split test files, see PR #288
=> Add length to Ruby CodeArea object 

dart/test/decode_test.dart, dart/test/encode_test.dart
=> Update dart tests for encoding/decoding split

rust/tests/all_test.rs
=> Update Rust tests for split encoding/decoding tests

cpp/openlocationcode_test.cc
=> Update C++ for split encoding/decoding tests

python/openlocationcode_test.py, test_data/encoding.csv
=> Update Python for split encoding and decoding tests

js/closure/openlocationcode_test.js
Update closure to run tests from encoding and decoding CSV files.
=> Update closure for split tests

java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
=> Revert #217 to more precisely handle floating point arithmetic.

.travis.yml, c/.clang-format, c/README.md, c/benchmark/bm-c.c, c/benchmark/shared.c, c/clang_check.sh, c/example.c, c/olc.c, c/olc.h, c/olc_private.h, c/olc_test.c, c/tests.h
Format code using Google style, add TravisCI checks.
=> Format c code with clang

.travis.yml, ruby/README.md, ruby/lib/plus_codes.rb, ruby/lib/plus_codes/code_area.rb, ruby/lib/plus_codes/open_location_code.rb, ruby/open-location-code.gemspec, ruby/rubocop.yml, ruby/test/plus_codes_test.rb
Update Ruby library to fix issue #316 and #307.
Enforces formatting by [rubocop](https://github.com/rubocop-hq/rubocop).
=> Update ruby library to new algorithm

c/src/olc.c, c/src/olc_private.h
Update C to match C++ algorithm, to address #311.
=> Update C for floating point errors

docs/specification.md
=> docs(specification): fix typo in Digits section

go/encode.go
=> Normalize longitude once

plpgsql/README.md, plpgsql/pluscode_functions.sql, plpgsql/tests_script_l.sql
Classic functions : 
pluscode_isvalid()
pluscode_isshort()
pluscode_encode()
pluscode_decode()
pluscode_shorten()
pluscode_codearea()
pluscode_cliplatitude()
pluscode_normalizelongitude()
=> Pluscode implementation for plpgsql (PostgreSQL)

java/pom.xml
Closes #402 by adding licence information to the pom.xml file
=> Add licence information to pom.xml

python/openlocationcode/openlocationcode.py
Recreating changes by @bheliker to close https://github.com/google/open-location-code/pull/418
=> Closing #418

plpgsql/pluscode_functions.sql
Fixes #467
This PR rewrites the "pluscode_encode" function by porting the Python implementation to PL/pgSQL. The "pluscode_computeLatitudePrecision" function is also ported to mirror the Python implementation.
This PR fixes a bug in the "pluscode_decode" function, where the row and column place values were not being initialized correctly.
=> Fix PL/pgSQL encoding and decoding

rust/src/interface.rs
=> Rust: replace unnecessary call of unwrap with "if let"

FAQ.txt, README.md
This, in combination with an update to the wiki as detailed in #500, would allow to close the following issues:
- #398 
- #461 
- #497 
- #500
=> Short code clarification

docs/specification.md
Fixing edge case described in #483 by reverting conditional from "until less" to "while more".
=> Edge case while shortening

CONTRIBUTING.md, Documentation/Reference/App_Developers.md, Documentation/Reference/GIS_Software.md, Documentation/Reference/Using_Spreadsheets.md, Documentation/Reference/comparison.adoc, README.md, TESTING.md, java/README.md, js/closure/README.md
See #490 
Includes some minor format changes.
=> Update links to documentation and the repo

.github/workflows/main.yml, java/src/test/java/com/google/openlocationcode/TestUtils.java
Solves issue #644 
Since Bazel 6 runfiles are under _main, not the repo name.
=> Change bazel path to test data files for Java

TESTING.md
Issue #659 
Update testing information to reflect Bazel and Bazelisk usage.
=> Update testing information for Bazel and Bazelisk

.github/workflows/main.yml
=> update github workflow actions

rust/Cargo.toml, rust/src/interface.rs, rust/src/lib.rs, rust/src/private.rs, rust/tests/all_test.rs
Refactor and Update Dependencies for Rust Implementation of Open Location Codes
- Updated the dependencies to their latest versions.
- Refactored the code to ensure compatibility with the updated dependencies.
This update improves the overall stability and performance of the implementation by leveraging the latest features and fixes from the dependencies.
=> Rust: update dependencies and refactor code for compatibility

java/src/main/java/com/google/openlocationcode/OpenLocationCode.java
For issue #672 
This modifies the integer conversion in the Java implementation to resolve floating point precision inconsistencies.
It doesn't yet expose the integer-based encoding as a separate function as I'm hopeful we can resolve our problems without having to do that.
=> Modify integer conversion for Java library

js/src/openlocationcode.js
Left over from JS edits in #695
=> remove commented out code block

.github/workflows/main.yml, dart/README.md, dart/checks.sh, dart/lib/src/open_location_code.dart, dart/test/benchmark_test.dart, dart/test/encode_test.dart
For issue https://github.com/google/open-location-code/issues/672
This modifies the integer conversion in the Dart implementation to resolve floating point precision inconsistencies.
It doesn't yet expose the integer-based encoding as a separate function as I'm hopeful we can resolve our problems without having to do that.
=> Modify integer conversion for dart implementation

c/src/olc.c, cpp/openlocationcode.cc, dart/lib/src/open_location_code.dart, js/closure/openlocationcode.js, js/src/openlocationcode.js, ruby/lib/plus_codes/open_location_code.rb
Refactor encode methods to be more similar and consistent.
- C: no impact on benchmark.
- C++: reduced benchmark time from ~150 nsec per encoding to ~79 nsec.
- Dart: no impact
- JS: no impact
- JS/Closure: no impact
- Ruby: slight improvement (7.4 usec -> 7.0 usec)
=> refactor encode methods

java/src/main/java/com/google/openlocationcode/OpenLocationCode.java, js/closure/openlocationcode.js, js/src/openlocationcode.js
For issue #710 
Add `roundingAwayFromZero()` function to Java and JavaScript, and call it in the conversion from floating point to integer in the encode methods.
=> Implement rounding away from zero

c/openlocationcode_test.cc
=> fix c formatting
